/**
 * Reads *.meta.json files produced by download-images.ts and prints SQL UPDATEs
 * for state_legislator_images (local_filename, content_sha256, content_type, downloaded_at).
 *
 * Usage: pnpm state-leg-images:import-meta > meta-updates.sql
 */
import fs from "node:fs";
import path from "node:path";

function cliArgs(argv: string[]): string[] {
  return argv.slice(2).filter((a) => !/\.(ts|js)$/i.test(a));
}

type Meta = {
  ocd_person_id: string;
  content_sha256?: string;
  content_type?: string;
  local_filename?: string;
  downloaded_at?: string;
};

function parseArgs() {
  let dir = path.join(
    process.cwd(),
    "data",
    "state-legislator-images",
    "downloads",
  );
  const args = cliArgs(process.argv);
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--dir" && args[i + 1]) {
      dir = path.resolve(args[++i]!);
    }
  }
  return { dir };
}

function sqlString(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

function main() {
  const { dir } = parseArgs();
  if (!fs.existsSync(dir)) {
    console.error(`Missing ${dir}`);
    process.exit(1);
  }

  const files = fs.readdirSync(dir).filter((f) => f.endsWith(".meta.json"));
  console.log(
    "-- Generated by scripts/state-legislator-images/import-download-meta.ts",
  );
  console.log("BEGIN;\n");

  for (const f of files) {
    const raw = fs.readFileSync(path.join(dir, f), "utf8");
    let meta: Meta;
    try {
      meta = JSON.parse(raw) as Meta;
    } catch {
      continue;
    }
    const id = meta.ocd_person_id;
    if (!id) continue;
    const local = meta.local_filename ?? "";
    const sha = meta.content_sha256 ?? "";
    const ct = meta.content_type ?? "";
    const at = meta.downloaded_at ?? new Date().toISOString();

    console.log(`UPDATE state_legislator_images SET
  local_filename = ${sqlString(local)},
  content_sha256 = ${sqlString(sha)},
  content_type = ${sqlString(ct)},
  downloaded_at = ${sqlString(at)}::timestamptz
WHERE ocd_person_id = ${sqlString(id)};
`);
  }

  console.log("COMMIT;");
}

main();
