import type { Metadata } from "next";
import { Suspense } from "react";
import "./globals.css";
import Container from "./components/container";
import { ReactLenis } from "lenis/react";
import { fontVariables, publicSans } from "./fonts";
import { TransitionBackdrop } from "./components/transitionComponents/transitionBackdrop/transitionBackdrop";
import SharedChrome from "./components/header/sharedChrome";
export const metadata: Metadata = {
  title: "RepConnect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fontVariables}>
      <body className={`${publicSans.className} overflow-y-scroll`}>
        <ReactLenis root />
        <Container>
          <TransitionBackdrop />
          <Suspense fallback={null}>
            <SharedChrome />
          </Suspense>
          {children}
        </Container>
      </body>
    </html>
  );
}
