import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header/header";
import Container from "./components/container";
import { ReactLenis } from "lenis/react";
import { Montserrat, Merriweather_Sans } from "next/font/google";
import PageTransition from "./components/pageTransition";

const montserrat = Montserrat({
  subsets: ["latin"],
});

const merriweatherSans = Merriweather_Sans({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "RepConnect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={merriweatherSans.className}>
      <body className="overflow-y-scroll">
        <ReactLenis root />
        <Container>
          <Header />
          {children}
        </Container>
      </body>
    </html>
  );
}
