import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header";
import Container from "./components/container";

export const metadata: Metadata = {
  title: "RepConnect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-y-scroll">
        <Container>
          <Header />
          {children}
        </Container>
      </body>
    </html>
  );
}
